language: node_js
node_js:
  - "14.5.0"
script:
  - echo "Starting deploy!!!"
  - npm install -g firebase-tools hugo
after_success:
  - hugo && firebase deploy --token $FB_TOKEN -m "Deploy CI"
after_failure:
  - echo "Huston, we have a p roblem"