baseURL: "http://example.org/"
languageCode: "en-us"
title: "Bruno Gurgel (@bggo)"
theme: "toha"

googleAnalytics: UA-240354867

params:
  # enableBlogPost: true
  background: "assets/images/bg.png"
  author:
    name: "Bruno Gurgel"
    image: "assets/images/brunogurgel.jpeg"
    # give your some contact information. they will be used in the footer
    contactInfo:
      email: "bruno.gurgel@gmail.com"
    # a summary of what you do
    summary:
      - I am a Technology Evangelist
      - I work with Digital Transformation
      - I'm passionate about value aggregation thru technology
      - I've been in a huge personal transformation
      - I believe that companies must have bigger purposes on society
      - I'm willing to help you in your digital challenges
      - I'm willing to help you transform our world with lean tech
      - I'm willing help you to take better business decisions